name: Run Pytest

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Garante que o pytest seja instalado
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Verify pytest installation
        run: pytest --version

      - name: Run tests with pytest
        run: pytest tests/
